name: project1_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  serverpod_flutter: 1.2.7
  project1_client:
    path: ../project1_client
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  intl: ^0.18.1
  injectable:
  get_it: ^7.7.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  build_runner:
  flutter_gen_runner:
  injectable_generator:

flutter:
  uses-material-design: true
  generate: true
